title: Anna Aalto
description: Anna Aalto - Artist based in Helsinki, Finland.
baseurl: ""
url: ""

# SEO metadata
author: Anna Aalto
location: Helsinki, Finland
social:
  name: Anna Aalto
  links:
    - https://instagram.com/paintings_by_anna_aalto

# Default social sharing image
image: /assets/images/generated/15.+Kesäkuu,+yöllä.jpg

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll_picture_tag
  - jekyll-sitemap

sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - assets/scss
  sourcemap: never

collections:
  artworks:
    output: false

picture:
  source: "assets/images/src"
  output: "assets/images/generated"
  markup: "html"
  presets:
    thumb:
      formats: [webp, jpeg]
      widths: [320, 640]
      fallback_width: 640
      attributes:
        loading: lazy
    gallery:
      formats: [webp, jpeg]
      widths: [480, 768, 1024, 1400, 1800, 2400]
      fallback_width: 1400
      attributes:
        loading: lazy
    hero:
      formats: [webp, jpeg]
      widths: [640, 960, 1280, 1600, 2000]
      fallback_width: 1280
      img_attributes:
        decoding: async

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
