title: Anna Aalto
description: Anna Aalto - Artist Portfolio
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll_picture_tag
  - jekyll-sitemap

sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - assets/scss
  sourcemap: never

collections:
  artworks:
    output: false

picture:
  source: "assets/images/src"
  output: "assets/images/generated"
  markup: "html"
  presets:
    thumb:
      formats: [webp, jpeg]
      widths: [320, 640]
      fallback_width: 640
      attributes:
        loading: lazy
    hero:
      formats: [avif, webp, jpeg]
      widths: [640, 960, 1280, 1600, 2000]
      fallback_width: 1280
      img_attributes:
        decoding: async

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
